{
 "title": "Kubotan - Inspect Microservice",
 "tags": [ "kubotan" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "microservice",
    "query": "label_values(container_spec_memory_limit_bytes{image=~\"chromeriver.*\",namespace=\"$namespace\"}, container_name)"
   },
   {
    "name": "pod",
    "query": "label_values(container_spec_memory_limit_bytes{image=~\"chromeriver/$microservice.*\",namespace=\"$namespace\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Deployed in $namespace",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (container_name,pod,crver) (\n  label_replace(\n    label_replace(\n      kube_pod_container_info{namespace=\"$namespace\",image=~\"^chromeriver/$microservice.*\"},\n      \"crver\", \"$1\", \"image\", \".*:([a-zA-Z0-9.]*)\"\n    ),\n    \"container_name\", \"$1\", \"image\", \"^chromeriver/([a-zA-Z0-9-]*).*\"\n  )\n) \n* on (pod) group_left(pod_ip) (\n  kube_pod_info{namespace=\"$namespace\"}\n)\n"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"$pod.*\"}) by (pod)"
    }
   ]
  },
  { "title": "Pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "pod" },
  {
   "title": "CPU usage: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"}[2m])) by (pod_name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_spec_cpu_quota{image=~\"chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"} / 100000",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"}) by (pod_name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_spec_memory_limit_bytes{image=~\"chromeriver/$microservice.*\",namespace=\"$namespace\",pod_name=\"$pod\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Pod metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU usage: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"}[2m])) by (pod_name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_spec_cpu_quota{image=~\"chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"} / 100000",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory usage: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",pod_name=\"$pod\"}) by (pod_name)",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_spec_memory_limit_bytes{image=~\"chromeriver/$microservice.*\",namespace=\"$namespace\",pod_name=\"$pod\"}",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}