{
 "title": "Kubotan - CR Microservices",
 "tags": [ "kubotan" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "microservice",
    "query": "label_values(container_spec_memory_limit_bytes{image=~\"chromeriver.*\",namespace=\"$namespace\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Deployed in $namespace",
   "type": "table",
   "gridPos": { "h": 21, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (container_name, crver) (label_replace(label_replace(kube_pod_container_info{namespace=\"$namespace\",image=~\"^chromeriver/$microservice.*\"}, \"crver\", \"$1\", \"image\", \".*:([a-zA-Z0-9.]*)\"), \"container_name\", \"$1\", \"image\", \"^chromeriver/([a-zA-Z0-9-]*).*\"))"
    }
   ]
  },
  {
   "title": "Pods CPU usage (2m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image=~\"^chromeriver/$microservice.*\",namespace=\"$namespace\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pods network I/O (2m avg) NEEDS FILTERING FOR CR ONLY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",namespace=\"$namespace\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\",pod_name=~\"^$microservice.*\"}[2m])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",namespace=\"$namespace\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$node$\",pod_name=~\"^$microservice.*\"}[2m])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  }
 ]
}