{
 "title": "Kubotan - Inspect Node",
 "tags": [ "kubotan" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu{mode!=\"idle\", mode!=\"iowait\", kubernetes_node=\"$node\",mode!~\"^(?:guest.*)$\"}[5m]))\nby (kubernetes_node)",
     "legendFormat": "Usage"
    },
    {
     "expr": "kube_node_status_allocatable_cpu_cores{job=\"kubernetes-service-endpoints\",node=\"$node\"}",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{job=\"kubernetes-service-endpoints\",node=\"$node\"}) by (node)",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$node\"} - node_memory_MemAvailable_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{kubernetes_node=\"$node\"}",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{job=\"kubernetes-service-endpoints\",node=\"$node\"}) by (node)",
     "legendFormat": "Requested"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pods running on: $node",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (namespace,pod) (avg by(node,pod,namespace)(kube_pod_info{node=\"$node\"})\n* on(pod, namespace) \ngroup_left(node) kube_pod_status_phase{phase=\"Running\"}\n* on(pod)\ngroup_right(kubernetes_name) kube_pod_container_status_restarts_total)"
    }
   ]
  }
 ]
}