{
 "title": "Kubotan - Nodes",
 "tags": [ "kubotan" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number Of Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Nodes Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Out of Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
    }
   ]
  },
  {
   "title": "Nodes Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node Stats",
   "type": "table",
   "description": "This table shows the comparison of CPU and RAM requests by applications, vs the capacity of the node",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_cpu_cores) by (node) \n  /\n  sum(kube_node_status_allocatable_cpu_cores) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "( \n  sum(kube_pod_container_resource_requests_memory_bytes) by (node) \n  /\n  sum(kube_node_status_allocatable_memory_bytes) by (node)\n) * 100",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes) by (node)",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by(node)(avg by(node,pod,namespace)(kube_pod_info{}) * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Running\"}) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by(node)(avg by(node,pod,namespace)(kube_pod_info{}) * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Pending\"}) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by(node)(avg by(node,pod,namespace)(kube_pod_info{}) * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Failed\"}) ",
     "legendFormat": "{{ node }}"
    },
    {
     "expr": "sum by(node)(avg by(node,pod,namespace)(kube_pod_info{}) * on(pod, namespace) group_right(node) kube_pod_status_phase{phase=\"Unknown\"}) ",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}