apiVersion: v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-prometheus:pod-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-prometheus
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
