apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: "kube-system"
  name: service-reader-kube-system
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services/proxy"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: api-prometheus:service-reader-kube-system
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-prometheus
  namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader-kube-system
  apiGroup: rbac.authorization.k8s.io
