---
# sudo yum install glibc-static
# sudo docker run -p 9093:9093 \
# --mount type=bind,source=/etc/alertmanager,target=/etc/alertmanager \
# -d prom/alertmanager \
# --config.file=/etc/alertmanager/alertmanager.yml \
# --web.external-url=https://prometheus.majustfortesting.com/am \
# --web.route-prefix=/
- name: Create Directories for Alertmanager.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
  with_items:
    - "{{ alertmanager_config_path }}"
    - "{{ alertmanager_data_path }}"

- name: Upload Files for Alertmanager.
  template:
    src: alertmanager.j2
    dest: "{{ alertmanager_config_path }}/alertmanager.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - "{{ alertmanager_restart_handler }}"

- name: Starting Alertmanager
  docker_container:
    name: "{{ alertmanager_container_name }}"
    image: "{{ alertmanager_docker_image }}:{{ alertmanager_docker_tag }}"
    ports:
      - "{{ alertmanager_port }}:{{ alertmanager_port }}"
    volumes:
      - "{{ alertmanager_config_path }}:{{ alertmanager_config_path }}:rw"
      - "{{ alertmanager_data_path }}:{{ alertmanager_data_path }}:rw"
    command: [ "--config.file={{ alertmanager_config_path }}/alertmanager.yml", "--storage.path={{ alertmanager_data_path }}", "--web.route-prefix=/", "--web.external-url=https://{{ prometheus_fqdn }}/am" ]
    state: started
