---
- name: Clean dashboards path
  file:
    state: absent
    path: "{{ grafana_dashboards_path }}/"

- name: Create Directories for Grafana
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0755
  with_items:
    - "{{ grafana_config_path }}"
    - "{{ grafana_config_path }}/provisioning"
    - "{{ grafana_config_path }}/provisioning/dashboards"
    - "{{ grafana_config_path }}/provisioning/datasources"
    - "{{ grafana_data_path }}"
    - "{{ grafana_dashboards_path }}"
    - "{{ grafana_log_path }}"

- name: Upload Files for Grafana
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_path }}/grafana.ini"
    owner: root
    group: root
    mode: 0644
  notify:
    - "{{ grafana_restart_handler }}"

- name: Starting Grafana
  docker_container:
    name: "{{ grafana_container_name }}"
    user: "{{ app_user }}:{{ app_group }}"
    image: "{{ grafana_docker_image }}:{{ grafana_docker_tag }}"
    ports:
      - "{{ grafana_port }}:{{ grafana_port }}"
    volumes:
      - "{{ grafana_config_path }}:{{ grafana_config_path }}:rw"
      - "{{ grafana_data_path }}:/var/lib/grafana:rw"
      - "{{ grafana_log_path }}:{{ grafana_log_path }}:rw"
    # env:
    #   GF_PATHS_CONFIG: "/monitoring/grafana/grafana.ini"
    state: started
